package geographiclib
//go:cgo_import_dynamic __stack_chk_fail __stack_chk_fail ""
//go:cgo_import_dynamic __stack_chk_guard __stack_chk_guard ""
//go:cgo_import_dynamic atan atan ""
//go:cgo_import_dynamic atan2 atan2 ""
//go:cgo_import_dynamic cos cos ""
//go:cgo_import_dynamic fmod fmod ""
//go:cgo_import_dynamic log log ""
//go:cgo_import_dynamic pow pow ""
//go:cgo_import_dynamic sin sin ""
//go:cgo_import_dynamic _ _ "/usr/lib/libc++.1.dylib"
//go:cgo_import_dynamic _ _ "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic _ _ "/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation"
//go:cgo_import_dynamic _ _ "/usr/lib/libobjc.A.dylib"
